language: python
dist: trusty
sudo: required
python:
- '3.3'
- '3.4'
- '3.5'
os:
- linux
before_install:
    - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
    - sudo apt-get update
    - sudo apt-get install -y git
    - sudo apt-get install -y cmake
    - sudo apt-get install -y gcc
    - sudo apt-get install -y zlib1g-dev
    - sudo apt-get install -y libgflags2 libgflags-dev
    - sudo apt-get install -y build-essential
    - sudo apt-get install -y libblas-dev
    - sudo apt-get install -y gcc-4.9 g++-4.9 cpp-4.9
    - sudo apt-get install -y libgtest-dev
    - export URL='https://github.com/JonathanRaiman/Dali/releases/download/v1.0.0/dali-1.0.0-Linux-x86_64-cpu.deb'
    - export FILE=`mktemp`
    - wget "$URL" -qO $FILE
    - sudo dpkg -i $FILE
    - rm $FILE
install:
    - pip3 install -r requirements.txt
    - python3 setup.py install
    - cp $(find . -name "core*.so") dali/
script: nose2
notifications:
    email:
        recipients:
        - szymon.sidor@gmail.com
        - jonathanraiman@gmail.com
        on_success: change
        on_failure: always
    slack:
        secure: UEkhyrjDPiwRYwLJ9yRNfH8iq57YdUKrQ2kY/trSaZTRv5cPGiUfoLYo1Vj65d8aGwyPeyWd/1/z4KOJ1+qWCIcqTLDrdrjig64v3qVfJt/054eEEUSGjMQgR9ureQ2DjR3fzbyJJLxt7IZJl8ytZtXLp13LpWBPJJOhKHcK1OLG70jUqPRj/cQ2RSFVLfcpvls+uJ8NHSJpM1434ML8DI/0Ucifp8j3NMi71odrTMcRl5AAouFgG5U5A9FvIKIIGAomArwaEKIIr+O/i10Gy6vKZxb82Hq+VQx6yow6mNEkvV40w9QZUmmTgXgsEgILcdMMeOw5iifPBg7wD1dEIBTN3PO+l+JXSv+CTx3sQdSWZb66ZSybWc6m8z5LnEGa1+ygagWBPs5CgzAXkmLQSkIdgocPCAMBSPxuxj2Hi+7s7SF8INut/aeP5/mCVxKRfcJo4Za56QTExXYqQPTQobdAKgoNOcwzK7nh2K2JDfh0qA8kaE59AZaQKnyZBLnFrQ4wSXHzcZ3kjF+nlQx/oFwQetFgu5ocNZQ5OFzToV+iLKBz+seoU0L1/e4Eweds+EjYtBHfqVB1hHmk4piFHgzQ8mC9WuL3Z9LZVRp4vykUb8yZrxbGB5Xc5WQfiAzXzsDYWDia4ZLKqcnPYq5fFw86gSf0gWCVZidVK33Yj3g=
